steps:
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   id: Set env and version in docker-compose
  #   entrypoint: /bin/sh
  #   args:
  #   - '-c'
  #   - |
  #     touch .env && \
  #     echo '' >> .env && \
  #     echo 'VUE_APP_FIREBASE_API_KEY=$_VUE_APP_FIREBASE_API_KEY' >> .env && \
  #     echo 'VUE_APP_FIREBASE_AUTH_DOMAIN=$_VUE_APP_FIREBASE_AUTH_DOMAIN' >> .env && \
  #     echo 'VUE_APP_FIREBASE_DATABASE_URL=$_VUE_APP_FIREBASE_DATABASE_URL' >> .env && \
  #     echo 'VUE_APP_FIREBASE_PROJECT_ID=$_VUE_APP_FIREBASE_PROJECT_ID' >> .env && \
  #     echo 'VUE_APP_FIREBASE_STORAGE_BUCKET=$_VUE_APP_FIREBASE_STORAGE_BUCKET' >> .env && \
  #     echo 'VUE_APP_FIREBASE_MESSAGING_SENDER_ID=$_VUE_APP_FIREBASE_MESSAGING_SENDER_ID' >> .env && \
  #     echo 'VUE_APP_FIREBASE_APP_ID=$_VUE_APP_FIREBASE_APP_ID' >> .env && \
  #     echo 'VUE_APP_FIREBASE_MEASUREMENT_ID=$_VUE_APP_FIREBASE_MEASUREMENT_ID' >> .env
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/orion-landing-$BRANCH_NAME:$COMMIT_SHA",
        ".",
      ]
  # Push the image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/orion-landing-$BRANCH_NAME:$COMMIT_SHA"]
  # Deploy image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "orion-landing-$BRANCH_NAME"
      - "--image"
      - "gcr.io/$PROJECT_ID/orion-landing-$BRANCH_NAME:$COMMIT_SHA"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--verbosity"
      - "debug"
images:
  - gcr.io/$PROJECT_ID/orion-landing-$BRANCH_NAME
