/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CiCloseBig: typeof import('~icons/ci/close-big')['default']
    CiMenuAlt02: typeof import('~icons/ci/menu-alt02')['default']
    CiWarningOutline: typeof import('~icons/ci/warning-outline')['default']
    Cliente: typeof import('./components/Cliente.vue')['default']
    Experience: typeof import('./components/Experience.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Hero: typeof import('./components/Hero.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    NavDrawer: typeof import('./components/NavDrawer.vue')['default']
    Partners: typeof import('./components/Partners.vue')['default']
    Personals: typeof import('./components/Personals.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WhyUs: typeof import('./components/WhyUs.vue')['default']
  }
}
